In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

## train_test_split

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [61]:
help(np.random.permutation)

Help on built-in function permutation:

permutation(...) method of numpy.random.mtrand.RandomState instance
    permutation(x)
    
    Randomly permute a sequence, or return a permuted range.
    
    If `x` is a multi-dimensional array, it is only shuffled along its
    first index.
    
    .. note::
        New code should use the ``permutation`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    x : int or array_like
        If `x` is an integer, randomly permute ``np.arange(x)``.
        If `x` is an array, make a copy and shuffle the elements
        randomly.
    
    Returns
    -------
    out : ndarray
        Permuted sequence or array range.
    
    See Also
    --------
    Generator.permutation: which should be used for new code.
    
    Examples
    --------
    >>> np.random.permutation(10)
    array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6]) # random
    
    >>> np.random.permutation([1, 4, 

In [62]:
len(X)

150

In [8]:
shuffle_indexes = np.random.permutation(len(X)) # 打乱索引

In [9]:
shuffle_indexes

array([145, 110,  86,  78, 127,  14, 132,  69,  36,  59,   7,  27,  66,
        20,  39,  91,  83, 143,  68,  90, 134, 138, 103, 112,  64, 130,
        43, 124,  42,  25,  95,  19,  35,  67,  65, 121, 116, 111,  60,
        26, 149, 129,  47,   1,  73, 141, 146, 135, 100,  15,  11,  53,
       102,  70,  29,  28,   3,  81,  13,  32,   9, 120,  21, 126,  87,
        71,  75, 104, 106, 101,  18,  61, 148, 140, 137,  55,  77,  40,
        97,  57,  10, 123, 105,  41,  37,  74,  16,  62,  45,  38, 119,
        94,  12, 147,  22,   5, 133,  92,   2,   0,  82,  31,  98, 128,
        93, 136,  50,  80,  88,  24,  79, 109,  96,  63,  46,  33, 117,
        44, 122,  84,   8,  89, 131,   6,  17,   4,  54,  99,  85, 118,
        76, 139, 114, 113,  34,  56, 125,  49, 107,  30, 108, 115,  48,
        72,  52,  58, 144,  51,  23, 142])

In [10]:
test_ratio = 0.2 # 20% 的测试数据
test_size = int(len(X) * test_ratio) # 本次实验测试数据的实际个数 150 * 20% = 30

In [11]:
test_size

30

In [69]:
test_indexes = shuffle_indexes[:test_size] # 测试数据的索引
train_indexes = shuffle_indexes[test_size:] # 训练数据的索引
test_indexes

array([145, 110,  86,  78, 127,  14, 132,  69,  36,  59,   7,  27,  66,
        20,  39,  91,  83, 143,  68,  90, 134, 138, 103, 112,  64, 130,
        43, 124,  42,  25])

In [13]:
X_train = X[train_indexes] # 获取X的训练数据
y_train = y[train_indexes] # 获取y的训练数据

X_test = X[test_indexes]
y_test = y[test_indexes]

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [15]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用我们的算法

In [72]:
from kNN.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [74]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [75]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [76]:
from kNN.kNN import KNNClassifier

In [77]:
my_knn_clf = KNNClassifier(k=3)

In [78]:
my_knn_clf.fit(X_train, y_train)

kNN(k=3)

In [79]:
y_predict = my_knn_clf.predict(X_test)

In [81]:
y_predict

array([2, 1, 1, 0, 1, 1, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2,
       0, 0, 2, 0, 0, 1, 2, 0])

In [82]:
y_test

array([2, 1, 2, 0, 1, 1, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2,
       0, 0, 2, 0, 0, 1, 2, 0])

In [83]:
np.sum(y_predict == y_test)

29

In [84]:
np.sum(y_predict == y_test) / len(y_test)

0.9666666666666667

## sklearn中的train_test_split

In [85]:
from sklearn.model_selection import train_test_split

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666) # test_size 测试比例， random_state相当于随机种子

In [88]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [89]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
