# Fancy Indexing

In [6]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
x[3]

3

In [8]:
x[3:9] # 注意分片是分到[n:m]中的m-1

array([3, 4, 5, 6, 7, 8])

In [9]:
x[3:9:2]

array([3, 5, 7])

In [10]:
[x[3], x[5], x[8]] # solution 1

[3, 5, 8]

In [11]:
ind = [3, 5, 8] # solution 2

In [12]:
x[ind]

array([3, 5, 8])

In [13]:
ind = np.array([[0,2],
                [1,3]])
x[ind] # 按照矩阵，把x的数值索引到矩阵中来

array([[0, 2],
       [1, 3]])

In [14]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col] # 对某个数组对应的索引感兴趣，比如矩阵中[0,1]--1，[1,2]--6

array([ 1,  6, 11])

In [16]:
X[0, col]

array([1, 2, 3])

In [17]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [18]:
col = [True, False, True, True] # 如果列是True或False，False就不存在

In [19]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

# numpy.array 的比较

In [20]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [22]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [23]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [24]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [25]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [26]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [27]:
2 * x == 24 - 4 * 4

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [28]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## numpy.array中比较的应用

In [30]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
np.sum(x <= 3)

4

In [32]:
np.count_nonzero(x <= 3) # 没有0的元素

4

In [33]:
np.any(x == 0) # 是否有任何的非0元素

True

In [34]:
np.any(x < 0)

False

In [35]:
np.all(x >= 0) # 所有的元素都>=0

True

In [36]:
np.all(x > 0) 

False

In [37]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.sum(X % 2 == 0)

8

In [39]:
np.sum(X % 2 == 0, axis = 1) # 每一行有多少偶数

array([2, 2, 2, 2])

In [40]:
np.sum(X % 2 == 0, axis = 0) # 每一列有多少偶数

array([4, 0, 4, 0])

In [41]:
np.all(X > 0, axis = 1)

array([False,  True,  True,  True])

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
np.sum((x > 3) & (x < 10)) # 注意：位运算符,左右比较的式子都是数组，得到的结果是一个索引，如果使用&&，比较的是逻辑，就会报错

6

In [44]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-44-d834f65999a2>, line 1)

In [45]:
np.sum((x%2 == 0) | (x > 10))

11

In [47]:
np.sum(~(x==0))

15

In [49]:
x[x < 5] # 小于5

array([0, 1, 2, 3, 4])

In [50]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [52]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
X[X[:,3] % 3 == 0, :] # 抽出最后一列能被3整除的行，和所有列

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

# Pandas