In [1]:
import numpy as np

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 基本属性

In [7]:
x.ndim

1

In [8]:
X.ndim

2

In [9]:
x.shape

(10,)

In [10]:
X.shape

(3, 5)

In [11]:
x.size

10

In [12]:
X.size

15

# numpy.array的数据访问

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[0]

0

In [15]:
x[-1]

9

In [16]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
X[0][0] #不建议

0

In [19]:
X[2, 2] # 建议！！

12

In [21]:
x[0:5]

array([0, 1, 2, 3, 4])

In [22]:
x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
x[::2]

array([0, 2, 4, 6, 8])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
X[:2][:3] #下列解析为什么不建议

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
X[:2] #前两行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
X[:2][:3]  # 解析X[:2]数组中的前3行元素，但是这个元素已经只有2行了！

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [31]:
X[0]

array([0, 1, 2, 3, 4])

In [32]:
X[0, :]

array([0, 1, 2, 3, 4])

In [33]:
X[0, :].ndim

1

In [34]:
X[:, 0]

array([ 0,  5, 10])

In [35]:
X[:, 0].ndim

1

In [36]:
X[1, 1]

6

In [37]:
X[:, 1]

array([ 1,  6, 11])

In [38]:
X[0, :]

array([0, 1, 2, 3, 4])

In [39]:
X[:, 2]

array([ 2,  7, 12])

In [40]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [42]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [44]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [46]:
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [47]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [48]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Reshape

In [50]:
x.shape

(10,)

In [51]:
x.ndim

1

In [52]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
B.ndim

2

In [60]:
B.shape

(1, 10)

In [61]:
x.shape

(10,)

In [62]:
x.reshape(10, -1) #只用关心行数，列数不管

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
C = x.reshape(10, -1)
C.shape

(10, 1)

In [64]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
x.reshape(3, -1) # 10不能被3整除

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

# 合并操作

In [67]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [68]:
x

array([1, 2, 3])

In [69]:
y

array([3, 2, 1])

## 开始合并

In [70]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [71]:
z = np.array([666,666,666])

In [74]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [76]:
A = np.array([[1,2,3],
          [4,5,6]])

In [77]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.concatenate([A,A], axis=1) # 沿着列的方向拼接

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [79]:
np.concatenate([A, z]) # 维数不一样

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [80]:
np.concatenate([A, z.reshape(1, -1)]) # z转换为列数不用管

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [88]:
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

## stack用法

In [89]:
np.vstack([A, z]) # 垂直方向智能的拼接在一起

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [91]:
B = np.full((2,2), 100)
B

array([[100, 100],
       [100, 100]])

In [92]:
np.hstack([A, B]) # 水平方向智能拼接在一起

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [93]:
np.hstack([A, z]) # 垂直可以，水平不可以的情况（因为z是一维数组）

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# 分割操作

In [94]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 开始分割

In [95]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [96]:
x1, x2, x3 = np.split(x, [3, 7])

In [97]:
x1

array([0, 1, 2])

In [98]:
x2

array([3, 4, 5, 6])

In [99]:
x3

array([7, 8, 9])

## 切割成两段

In [100]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [101]:
x1, x2 = np.split(x, [5])

In [102]:
x1

array([0, 1, 2, 3, 4])

In [103]:
x2

array([5, 6, 7, 8, 9])

## 分割矩阵

In [105]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
A1, A2 = np.split(A, [2])

In [108]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
A1, A2 = np.split(A, [2], axis=1) # 列方向分割

In [111]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [112]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## v/hsplit的用法

In [113]:
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [114]:
upper, lower = np.vsplit(A, [2])

In [115]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [116]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
left, right = np.hsplit(A, [2])

In [118]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [119]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# 意义
例如下列data，前3列可能代表3个同一种特征，最后一列表示和前3列不同的特征。
运行时就要进行分隔开。

In [120]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
x, y = np.hsplit(data, [-1])

In [122]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [123]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [124]:
y[:, 0]

array([ 3,  7, 11, 15])