# 聚合运算

In [179]:
import numpy as np
L = np.random.random(100)

In [180]:
L

array([0.95220163, 0.22987149, 0.79818371, 0.2134445 , 0.71473456,
       0.8907027 , 0.65287875, 0.22142482, 0.51029763, 0.5014755 ,
       0.20558397, 0.34396809, 0.54418135, 0.14525228, 0.84377447,
       0.33231967, 0.01377296, 0.64641222, 0.58434886, 0.18136501,
       0.48472089, 0.23750378, 0.90608181, 0.65920593, 0.59286988,
       0.4733383 , 0.39083505, 0.31898986, 0.52697992, 0.80860353,
       0.49469881, 0.99408709, 0.09615687, 0.8657713 , 0.44886055,
       0.38260396, 0.7316249 , 0.25630527, 0.99477222, 0.26593348,
       0.8803973 , 0.80804867, 0.87274893, 0.31040183, 0.33604306,
       0.45035599, 0.96603197, 0.33606735, 0.49081919, 0.77794633,
       0.77143965, 0.36136329, 0.08345463, 0.47481415, 0.16285321,
       0.86695851, 0.82593301, 0.42093658, 0.43680656, 0.9468347 ,
       0.20673901, 0.33083704, 0.0100096 , 0.10786354, 0.38520809,
       0.65454806, 0.69816495, 0.34536215, 0.15069999, 0.63021056,
       0.23361453, 0.241253  , 0.85340901, 0.80610956, 0.88646

In [181]:
sum(L)

50.70561985206878

In [182]:
np.sum(L)

50.705619852068764

In [183]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

56.3 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
811 µs ± 71.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [184]:
np.min(big_array)

1.3961568527953716e-06

In [185]:
np.max(big_array)

0.999998904397211

In [186]:
big_array.max()

0.999998904397211

In [187]:
big_array.min()

1.3961568527953716e-06

In [188]:
big_array.sum()

500142.19195131777

In [189]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [190]:
np.sum(X)

120

In [191]:
np.sum(X, axis=0) # 每一列的和

array([24, 28, 32, 36])

In [192]:
np.sum(X, axis=1) # 每一行的和

array([ 6, 22, 38, 54])

In [193]:
np.prod(X) # 计算所有元素的乘积

0

In [194]:
np.prod(X + 1) # 都加1了之后，计算所有元素的乘积

2004189184

In [195]:
np.mean(X) #平均数

7.5

In [196]:
np.median(X) # 中位数

7.5

In [197]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [198]:
np.median(v)

2.0

In [199]:
np.percentile(big_array, q=50) # 求百分位，意思是50%都是小于0.499的

0.4999421414108574

In [200]:
np.median(big_array)

0.4999421414108574

In [201]:
np.percentile(big_array, q=100)

0.999998904397211

In [202]:
np.max(big_array)

0.999998904397211

In [203]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.3961568527953716e-06
0.2497804073417703
0.4999421414108574
0.7502703033022531
0.999998904397211


In [204]:
np.var(big_array) #方差

0.08345345821236619

In [205]:
np.std(big_array) # 标准差

0.2888831220621347

In [206]:
x = np.random.normal(0, 1, size=1000000) # 均值为0，标准差为1的正态分布

In [207]:
np.mean(x) # 均值

-0.0004808896436468229

In [208]:
np.std(x) 

0.9997902854977494

# 索引

In [215]:
x

array([ 1.80793697, -0.23658344, -0.13697839, ..., -0.65258733,
        0.07083716,  0.20496639])

In [216]:
np.min(x)

-5.240820586489809

In [211]:
np.argmin(x) # 最小值的索引

630547

In [217]:
x[630547]

-5.240820586489809

In [218]:
np.argmax(x)

585452

In [219]:
x[585452]

4.751668785613369

In [220]:
np.max(x)

4.751668785613369

## 排序和使用索引 

In [158]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [159]:
np.random.shuffle(x) # 打乱顺序
x

array([ 4,  2,  0, 13,  1, 11,  3, 15, 10,  6,  5, 14,  9,  7,  8, 12])

In [160]:
np.sort(x) # 排序

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [161]:
x

array([ 4,  2,  0, 13,  1, 11,  3, 15, 10,  6,  5, 14,  9,  7,  8, 12])

In [162]:
x.sort()

In [163]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [164]:
X = np.random.randint(10, size=(4, 4))
X

array([[0, 3, 0, 6],
       [7, 0, 9, 7],
       [2, 2, 7, 4],
       [4, 6, 9, 1]])

In [165]:
np.sort(X) # 每一行进行排序

array([[0, 0, 3, 6],
       [0, 7, 7, 9],
       [2, 2, 4, 7],
       [1, 4, 6, 9]])

In [166]:
np.sort(X, axis=1) # 按行进行排序

array([[0, 0, 3, 6],
       [0, 7, 7, 9],
       [2, 2, 4, 7],
       [1, 4, 6, 9]])

In [167]:
np.sort(X, axis=0) # 按列进行排序

array([[0, 0, 0, 1],
       [2, 2, 7, 4],
       [4, 3, 9, 6],
       [7, 6, 9, 7]])

In [168]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [169]:
np.random.shuffle(x)

In [170]:
x

array([ 5,  4,  3, 14,  8,  0, 11,  6,  2, 12,  7,  9, 13, 15,  1, 10])

In [171]:
np.argsort(x) # 索引排序

array([ 5, 14,  8,  2,  1,  0,  7, 10,  4, 11, 15,  6,  9, 12,  3, 13],
      dtype=int64)

In [172]:
np.partition(x, 3) # 快速排序部分,3前面的数据都比3小，3后面的数据都比3大

array([ 1,  0,  2,  3,  5,  4,  6, 11,  8, 12,  7,  9, 13, 15, 14, 10])

In [173]:
np.argpartition(x, 3) # 快速排序部分，索引模式

array([14,  5,  8,  2,  0,  1,  7,  6,  4,  9, 10, 11, 12, 13,  3, 15],
      dtype=int64)

In [226]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [227]:
np.argsort(X, axis=1) # 按行排序

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [223]:
np.argsort(X, axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]], dtype=int64)

In [224]:
np.argpartition(X, 2, axis=1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [225]:
np.argpartition(X, 2, axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]], dtype=int64)