## 精准度和召回率的平衡

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

D:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [7]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [8]:
from sklearn.metrics import recall_score
recall_score(y_test, y_predict)

0.8

In [9]:
log_reg.decision_function(X_test) # 决策函数 （score值）

array([-21.4039773 , -32.89364379, -16.40026013, -79.8119307 ,
       -48.03932344, -24.18988984, -44.58965267, -24.26296011,
        -1.13818798, -18.99903758, -65.81660001, -50.96244729,
       -30.93812184, -45.94344658, -37.36250374, -29.49063477,
       -36.93675227, -82.78552967, -37.6088407 ,  -9.8882366 ,
        -9.25695136, -85.22873843, -16.74470907, -45.35010353,
        -5.02531081, -48.27450496, -11.66563   , -37.38507888,
       -25.08413934, -13.60371769, -16.60746266, -28.78342253,
       -34.3568379 , -28.52507657,  -8.09768697,  -4.57614058,
       -21.99777125, -21.87070461, -31.24135927, -23.3332075 ,
       -26.90193709, -62.23012639, -37.69699401, -66.36770954,
       -20.09366913, -16.70960696, -18.15725897, -21.55490981,
       -28.96788245, -19.62058144,   2.39045001,   7.7395625 ,
       -34.8902543 , -42.70552778, -25.61609234, -34.73810303,
        -7.59872931, -49.49644725, -51.52689491,  19.6502314 ,
       -10.06665878, -31.99166273, -11.49844235,  -1.39

In [10]:
log_reg.decision_function(X_test)[:10]

array([-21.4039773 , -32.89364379, -16.40026013, -79.8119307 ,
       -48.03932344, -24.18988984, -44.58965267, -24.26296011,
        -1.13818798, -18.99903758])

In [11]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
decision_scores = log_reg.decision_function(X_test)

In [13]:
np.min(decision_scores)

-85.70965471439519

In [14]:
np.max(decision_scores)

19.872945055314357

In [15]:
# 阈值调高
y_predict2 = np.array(decision_scores >= 5, dtype='int')

In [16]:
confusion_matrix(y_test, y_predict2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [18]:
precision_score(y_test, y_predict2)

0.96

In [19]:
recall_score(y_test, y_predict2)

0.5333333333333333

In [22]:
#阈值调低
y_predict3 = np.array(decision_scores >= -5, dtype='int')

In [23]:
confusion_matrix(y_test, y_predict3)

array([[390,  15],
       [  5,  40]], dtype=int64)

In [24]:
precision_score(y_test, y_predict3)

0.7272727272727273

In [25]:
recall_score(y_test, y_predict3)

0.8888888888888888