In [4]:
import numpy as np

In [9]:
a = np.array([
    [5],
    [3],
    [5],
    [3]
])
b = a.T
print(a)
print(b)

[[5]
 [3]
 [5]
 [3]]
[[5 3 5 3]]


In [10]:
a.dot(b)

array([[25, 15, 25, 15],
       [15,  9, 15,  9],
       [25, 15, 25, 15],
       [15,  9, 15,  9]])

In [11]:
import torch

In [15]:
a = torch.tensor([-100])
torch.nn.Softmax(a)

Softmax(dim=tensor([-100]))