In [4]:
import torch

In [5]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8]).view(4, 2)
x

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [6]:
x = torch.roll(x, shifts=1, dims=0)
x

tensor([[7, 8],
        [1, 2],
        [3, 4],
        [5, 6]])

In [7]:
x = torch.roll(x, shifts=-1, dims=0)
x

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])