In [4]:
import torch
import torch.nn as nn

In [6]:
nn.Parameter(torch.zeros(1))

Parameter containing:
tensor([0.], requires_grad=True)

In [9]:
sm = nn.Softmax(dim=-1)
a = torch.rand(2, 3)
print(a)
print(sm(a))

tensor([[0.6901, 0.5918, 0.3898],
        [0.0513, 0.6428, 0.0659]])
tensor([[0.3778, 0.3424, 0.2798],
        [0.2617, 0.4728, 0.2655]])
