In [1]:
import numpy

In [2]:
numpy.__version__

'1.20.1'

In [3]:
import numpy as np

In [4]:
numpy.__version__

'1.20.1'

In [5]:
L = [i for i in range(10)]

In [6]:
L[5]

5

In [7]:
L[5] = 100

In [26]:
L[5] = 'machine learning'
L

[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

In [9]:
import array

In [10]:
arr = array.array('i', [i for i in range(10)])

In [11]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5]

5

In [14]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [15]:
arr[5] = 'machine learning'

TypeError: an integer is required (got type str)

## numpy.array

In [16]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr[5]

5

In [18]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [19]:
nparr[5] = 'machine learning'

ValueError: invalid literal for int() with base 10: 'machine learning'

In [20]:
nparr.dtype

dtype('int32')

In [22]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [23]:
nparr2 = np.array([1, 2, 3.0])

In [24]:
nparr2.dtype

dtype('float64')

In [29]:
np.zeros(10).dtype

dtype('float64')

In [28]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.zeros(shape=(3,5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.full(shape=(3,5), 666)

SyntaxError: positional argument follows keyword argument (<ipython-input-34-086724a3e30f>, line 1)

In [35]:
np.full(shape=(3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [36]:
[i in range(0, 20, 2)]

NameError: name 'i' is not defined

In [37]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [38]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [40]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [42]:
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

## random

In [43]:
np.random.randint(0, 10)

3

In [44]:
np.random.randint(0, 10, 10)

array([3, 3, 2, 2, 2, 0, 9, 6, 0, 8])

In [45]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.random.randint(4, 8, size = 10)

array([7, 5, 4, 6, 7, 6, 6, 5, 6, 5])

In [47]:
np.random.randint(0, 10, size=(3,5))

array([[6, 4, 4, 2, 0],
       [7, 0, 3, 0, 5],
       [1, 9, 0, 6, 7]])

In [48]:
np.random.seed(666)

In [49]:
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [50]:
np.random.seed(666)

In [51]:
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [52]:
np.random.randint(0, 10, size=(3,5))

array([[4, 4, 0, 0, 4],
       [0, 4, 5, 7, 1],
       [0, 0, 6, 6, 0]])

In [53]:
np.random.random()

0.8888993137763092

In [54]:
np.random.random(10)

array([0.62640453, 0.81887369, 0.54734542, 0.41671201, 0.74304719,
       0.36959638, 0.07516654, 0.77519298, 0.21940924, 0.07934213])

In [56]:
np.random.random((3,5))

array([[0.48678052, 0.1536739 , 0.82846513, 0.19136857, 0.27040895],
       [0.56103442, 0.90238039, 0.85178834, 0.41808196, 0.39347627],
       [0.01622051, 0.29921337, 0.35377822, 0.89350267, 0.78613657]])

In [57]:
np.random.normal()

-0.4264736981002289

In [58]:
np.random.normal(10, 100)

154.77350573628146

In [59]:
np.random.normal(0, 1, (3,5))

array([[-0.1963061 ,  1.51814514,  0.07722188, -0.06399132,  0.94592341],
       [ 1.20409101, -0.45124074, -1.58744651, -1.86885548,  0.10037737],
       [-3.09487059,  3.39351678, -0.12666878, -0.93713026,  0.56552529]])

In [60]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution

In [1]:
1+2

3