## 池化层
---

### 二维最大池化层和平均池化层

In [1]:
import torch
from torch import nn

def pool2d(X, pool_size, mode='max'):
    X = X.float()
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1] - p_w + 1) # 构建卷积后的大小
    for i in range(Y.shape[0]): # 卷积核为（2，2），原输入fm为(3,3)的话，就需要Y.shape[0] -- 4次卷积
        for j in range(Y.shape[1]): # 卷积核数量 -- 4，挨个遍历
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [2]:
X = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
pool2d(X, (2,2))

tensor([[4., 5.],
        [7., 8.]])

In [3]:
pool2d(X, (2,2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

### 填充和步幅

In [4]:
X = torch.arange(16, dtype=torch.float).view((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [5]:
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [7]:
# h: (4 - 2 + 1 + 2) / 2
# w: (4 - 4 + 2 + 3) / 3
pool2d = nn.MaxPool2d((2,4), padding=(1,2), stride=(2,3))
pool2d(X)
# 4 - 2 + 2 + 1 = 5
# 4 - 4 + 4 + 1 = 5

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])